### ISSUE TITLE
Plugin Requires Header Information

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre-Wordpress-Plugin#2]
abre-directory.php needs the following added in order to be uploaded into WP:

/**
 * Plugin Name: Abre Directory
 * Plugin URI: https://github.com/abreio/Abre-Wordpress-Plugin
 * Description: Integrated Abre's Directory App with WordPress Sites
 * Version: 1.0
 * Author: Abre
 * Author URI: http://www.abre.io
 */

**Comment by hcsdrose** [comment]
Added.
